services:
  db-bible:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./db-entrypoint:/docker-entrypoint-initdb.d
    ports:
      - 55434:5432
    networks:
      - bible-network
      - cloudbeaver
  app:
    container_name: "biblia_filipelopesme_fastapi"
    env_file:
      - .env
    build: .
    restart: always
    volumes:
      - .:/src
      - ./data/biblia:/initial_data
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - db-bible
    networks:
      - bible-network
      - ollama
      - qdrant

networks:
  bible-network:
    name: "bible-net"
    driver: bridge
  cloudbeaver:
    external: true
  ollama:
    external: true
  qdrant:
    name: "qdrant_default"
    external: true
    
