version: "3.8"
services:
  app:
    container_name: "biblia_filipelopesme_fastapi"
    env_file:
      - .env
    build: .
    volumes:
      - .:/src
      - ./data/biblia:/initial_data
    ports:
      - ${APP_PORT}:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    