"""add active field to versao table

Revision ID: 072cbcf3322d
Revises: 11a63d662104
Create Date: 2025-10-05 20:53:29.456905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072cbcf3322d'
down_revision: Union[str, None] = '11a63d662104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versao', sa.Column('active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('versao', 'active')
    # ### end Alembic commands ###
