"""initial migration

Revision ID: 11a63d662104
Revises: 
Create Date: 2024-03-17 14:07:15.201758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '11a63d662104'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abrev', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abrev', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('testamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['testamento_id'], ['testamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livrocapitulonumeroversiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitulo', sa.Integer(), nullable=False),
    sa.Column('total_versiculos', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['livro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitulo', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('texto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('versao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['livro.id'], ),
    sa.ForeignKeyConstraint(['versao_id'], ['versao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verse')
    op.drop_table('bookchapternumberverse')
    op.drop_table('book')
    op.drop_table('version')
    op.drop_table('testament')
    # ### end Alembic commands ###
