"""add_strongs_tables

Revision ID: 25bc0bd9b8f0
Revises: ad473925f962
Create Date: 2025-12-29 13:26:25.155650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '25bc0bd9b8f0'
down_revision: Union[str, None] = 'ad473925f962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strongs_entry',
    sa.Column('strong', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lemma', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transliteration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pronunciation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('derivation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('def_short', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('def_long', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('strong')
    )
    op.create_table('original_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('capitulo', sa.Integer(), nullable=False),
    sa.Column('versiculo', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('surface', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strong', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('morph', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['livro_id'], ['livro.id'], ),
    sa.ForeignKeyConstraint(['strong'], ['strongs_entry.strong'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_original_token_capitulo'), 'original_token', ['capitulo'], unique=False)
    op.create_index(op.f('ix_original_token_livro_id'), 'original_token', ['livro_id'], unique=False)
    op.create_index(op.f('ix_original_token_strong'), 'original_token', ['strong'], unique=False)
    op.create_index(op.f('ix_original_token_versiculo'), 'original_token', ['versiculo'], unique=False)
    # op.drop_index('idx_versiculo_texto_gin', table_name='versiculo', postgresql_ops={'texto': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('idx_versiculo_texto_gin', 'versiculo', ['texto'], unique=False, postgresql_ops={'texto': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_original_token_versiculo'), table_name='original_token')
    op.drop_index(op.f('ix_original_token_strong'), table_name='original_token')
    op.drop_index(op.f('ix_original_token_livro_id'), table_name='original_token')
    op.drop_index(op.f('ix_original_token_capitulo'), table_name='original_token')
    op.drop_table('original_token')
    op.drop_table('strongs_entry')
    # ### end Alembic commands ###
