"""remove unused models

Revision ID: ad473925f962
Revises: 29b56651e3a8
Create Date: 2025-10-06 03:01:35.491687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad473925f962'
down_revision: Union[str, None] = '29b56651e3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nota')
    op.drop_index('ix_etiqueta_nome', table_name='etiqueta')
    op.drop_table('etiqueta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiqueta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='etiqueta_pkey')
    )
    op.create_index('ix_etiqueta_nome', 'etiqueta', ['nome'], unique=False)
    op.create_table('nota',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conteudo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='nota_pkey')
    )
    # ### end Alembic commands ###
